SensorLED:
    Enabled: true
    RunUpDelay: 5ms
    RunDownDelay: 20ms
    HoldTime: 10s
    LedRGB: [70, 70, 70]
    LatchEnabled: true
    LatchTriggerValue: 512
    LatchTriggerDelay: 3s
    LatchTime: 5m0s
    LatchLedRGB: [140, 140, 140]
NightLED:
    Enabled: true
    Latitude: 49.014
    Longitude: 8.4043
    LedRGB: [[1, 0, 0], [1, 0, 0], [0, 0, 20]]
ClockLED:
    Enabled: true
    StartLedHour: 0
    EndLedHour: 69
    StartLedMinute: 111
    EndLedMinute: 164
    LedHour: [50, 30, 0]
    LedMinute: [50, 30, 0]
AudioLED:
    Enabled: true
    Device: squeezelite
    StartLedLeft: 69
    EndLedLeft: 0
    StartLedRight: 111
    EndLedRight: 164
    LedGreen: [0, 80, 0]
    LedYellow: [40, 40, 0]
    LedRed: [100, 0, 0]
    SampleRate: 48000
    FramesPerBuffer: 2048
    UpdateFreq: 30ms
    MinDB: -60
    MaxDB: -3
CylonLED:
    Enabled: true
    Duration: 50s
    Delay: 20ms
    Step: 1.7
    Width: 7
    LedRGB: [75, 0, 0]
MultiBlobLED:
    Enabled: true
    Duration: 1m40s
    Delay: 120ms
    BlobCfg: [{DeltaX: 0.9, X: 20, Width: 512, LedRGB: [30, 0, 0]}, {DeltaX: -0.5, X: 40, Width: 512, LedRGB: [0, 30, 0]}, {DeltaX: 0.4, X: 130, Width: 768, LedRGB: [0, 0, 40]}, {DeltaX: -0.2, X: 150, Width: 512, LedRGB: [30, 0, 25]}]
Hardware:
    LEDType: ws2801
    SPIFrequency: 2097152
    Display:
        ForceUpdateDelay: 1s
        LedsTotal: 165
        ColorCorrection: [1, 0.175, 0.05]
        APA102_Brightness: 31
        LedSegments: {GroupA: [{FirstLed: 0, LastLed: 69, SpiMultiplex: L1, Reverse: false}, {FirstLed: 111, LastLed: 164, SpiMultiplex: L2, Reverse: false}]}
    Sensors:
        SmoothingSize: 3
        LoopDelay: 50ms
        SensorCfg:
            S0:
                LedIndex: 0
                SpiMultiplex: ADC1
                AdcChannel: 0
                TriggerValue: 130
            S1:
                LedIndex: 69
                SpiMultiplex: ADC1
                AdcChannel: 7
                TriggerValue: 130
            S2:
                LedIndex: 111
                SpiMultiplex: ADC2
                AdcChannel: 0
                TriggerValue: 150
            S3:
                LedIndex: 164
                SpiMultiplex: ADC2
                AdcChannel: 5
                TriggerValue: 150
    SpiMultiplexGPIO:
        ADC1:
            Low: [17, 22, 23]
            High: [24]
        ADC2:
            Low: [17, 22, 24]
            High: [23]
        L1:
            Low: [17]
            High: [22, 23, 24]
        L2:
            Low: [22]
            High: [17, 23, 24]
Logging:
    TUI:
        Level: INFO
        Format: text
        File: /tmp/goleds.log
    HW:
        Level: INFO
        Format: text
        File: /var/log/goleds.log
