SensorLED:
  Enabled: true
  RunUpMillis: 3 
  RunDownMillis: 20
  HoldSeconds: 10
  LedRGB: [80, 15, 3]

NightLED:
  Enabled: true
  Latitude: 49.014
  Longitude: 8.4043
  LedRGB: [4, 0, 0]

HoldLED:
  Enabled: true
  HoldMinutes: 5
  TriggerSeconds: 3
  TriggerValue: 160
  LedRGB: [140, 25, 6]

Hardware:
  Display:
    ForceUpdateSeconds: 1
    LedsTotal: 125
  Sensors:
    SmoothingSize: 3
    LoopDelayMillis: 5
    SensorCfg:
      S0:
        LedIndex: 0
        Adc: 0
        AdcChannel: 0
        TriggerValue: 40
      S1:
        LedIndex: 69
        Adc: 0
        AdcChannel: 7
        TriggerValue: 50
      S2:
        LedIndex: 70
        Adc: 1
        AdcChannel: 0
        TriggerValue: 60
      S3:
        LedIndex: 124
        Adc: 1
        AdcChannel: 5
        TriggerValue: 50
