SensorLED:
  Enabled: true
  RunUpDelay: 5ms
  RunDownDelay: 20ms
  HoldTime: 10s
  LedRGB: [80, 15, 3]

NightLED:
  Enabled: true
  Latitude: 49.014
  Longitude: 8.4043
  LedRGB:
    - [3, 0, 0]
    - [0, 0, 1]

HoldLED:
  Enabled: true
  HoldTime: 5m
  TriggerDelay: 3s
  TriggerValue: 160
  LedRGB: [140, 25, 6]

MultiBlobLED:
  Enabled: true 
  Delay: 20ms
  BlobCfg:
    BlobRed:                    
      DeltaX: 0.1
      X: 20
      Width: 512
      LedRGB: [20, 0, 0]
    BlobGreen:
      DeltaX: 0.2
      X: 70
      Width: 512
      LedRGB: [0, 10, 0]
    BlobBlue:
      DeltaX: -0.1
      X: 110
      Width: 512 
      LedRGB: [0, 0, 6]

# BlobLED:
#   Enabled: false 
#   BlobCfg:
#     BlobRed:                    
#       Delay: 100ms
#       DeltaX: 0.1
#       X: 20
#       Width: 512
#       LedRGB: [20, 0, 0]
#     BlobGreen:
#       Delay: 80ms
#       DeltaX: 0.1
#       X: 70
#       Width: 512
#       LedRGB: [0, 10, 0]
#     BlobBlue:
#       Delay: 80ms
#       DeltaX: -0.1
#       X: 110
#       Width: 512 
#       LedRGB: [0, 0, 6]

Hardware:
  GPIOLibrary: "default"
  SPIFrequency: 2097152
  Display:
    ForceUpdateDelay: 1000ms
    LedsTotal: 125
  Sensors:
    SmoothingSize: 3
    LoopDelay: 10ms
    SensorCfg:
      S0:
        LedIndex: 0
        Adc: 0
        AdcChannel: 0
        TriggerValue: 47
      S1:
        LedIndex: 69
        Adc: 0
        AdcChannel: 7
        TriggerValue: 50
      S2:
        LedIndex: 70
        Adc: 1
        AdcChannel: 0
        TriggerValue: 60
      S3:
        LedIndex: 124
        Adc: 1
        AdcChannel: 5
        TriggerValue: 52
