SensorLED:
  Enabled: true
  RunUpMillis: 5
  RunDownMillis: 30
  HoldSeconds: 10
  LedRGB: [80, 15, 3]

NightLED:
  Enabled: true
  Latitude: 49.014
  Longitude: 8.4043
  LedRGB: [4, 0, 0]

HoldLED:
  Enabled: true
  HoldMinutes: 5
  TriggerSeconds: 3
  TriggerValue: 160
  LedRGB: [140, 25, 6]

Hardware:
  Display:
    LedsTotal: 125
  Sensors:
    TriggerLeft: 40
    TriggerMidLeft: 50
    TriggerMidRight: 60
    TriggerRight: 55
    SmoothingSize: 3
    LoopDelayMillis: 5 
