SensorLED:
  Enabled: true
  RunUpDelay: 5ms
  RunDownDelay: 20ms
  HoldTime: 10s
  LedRGB: [80, 15, 3]

NightLED:
  Enabled: true
  Latitude: 49.014
  Longitude: 8.4043
  LedRGB:
    - [3, 0, 0]
    - [0, 0, 1]

HoldLED:
  Enabled: true
  HoldTime: 5m
  TriggerDelay: 3s
  TriggerValue: 160
  LedRGB: [140, 25, 6]

BlobLED:
  # leave it disabled for now, not working correctly
  Enabled: false 
  BlobCfg:
    Blob1:
      Delay: 200ms
      DeltaX: 0.5
      X: 30
      Width: 64
      LedRGB: [60, 0, 0]
    Blob2:
      Delay: 200ms
      DeltaX: -0.3
      X: 90
      Width: 128
      LedRGB: [60, 0, 0]

Hardware:
  GPIOLibrary: "periph.io"
  SPIFrequency: 2097152
  SPIDelay: 1µs 
  Display:
    ForceUpdateDelay: 1000ms
    LedsTotal: 125
  Sensors:
    SmoothingSize: 3
    LoopDelay: 10ms
    SensorCfg:
      S0:
        LedIndex: 0
        Adc: 0
        AdcChannel: 0
        TriggerValue: 47
      S1:
        LedIndex: 69
        Adc: 0
        AdcChannel: 7
        TriggerValue: 50
      S2:
        LedIndex: 70
        Adc: 1
        AdcChannel: 0
        TriggerValue: 60
      S3:
        LedIndex: 124
        Adc: 1
        AdcChannel: 5
        TriggerValue: 52
