SensorLED:
  Enabled: true
  RunUpDelay: 5ms
  RunDownDelay: 20ms
  HoldTime: 10s
  LedRGB: [70, 70, 70]

NightLED:
  Enabled: true
  Latitude: 49.014
  Longitude: 8.4043
#  Longitude: -172.0
  LedRGB:
    - [1, 0, 0]
    - [1, 0, 0]
    - [0, 0, 20]

HoldLED:
  Enabled: true
  HoldTime: 5m
  TriggerDelay: 3s
  TriggerValue: 160
  LedRGB: [140, 140, 140]

CylonLED:
  Enabled: true
  Duration: 120s
  Delay: 30ms
  Step: 1.7
  Width: 7
  LedRGB: [255, 0, 0]

MultiBlobLED:
  Enabled: false
  Trigger: true
  Duration: 120s
  Delay: 120ms
  BlobCfg:
    BlobRed:                    
      DeltaX: 0.3
      X: 20
      Width: 512
      LedRGB: [30, 0, 0]
    BlobGreen:
      DeltaX: 0.5
      X: 50
      Width: 512
      LedRGB: [0, 30, 0]
    BlobBlue:
      DeltaX: -0.3
      X: 90
      Width: 768 
      LedRGB: [0, 0, 40]
    BlobRed2:
      DeltaX: 0.3
      X: 110
      Width: 512 
      LedRGB: [30, 0, 0]

Hardware:
  SPIFrequency: 2097152
  Display:
    ForceUpdateDelay: 1000ms
    LedsTotal: 125
    ColorCorrection: [1, 0.175, 0.05]
  Sensors:
    SmoothingSize: 3
    LoopDelay: 10ms
    SensorCfg:
      S0:
        LedIndex: 0
        Adc: 0
        AdcChannel: 0
        TriggerValue: 47
      S1:
        LedIndex: 69
        Adc: 0
        AdcChannel: 7
        TriggerValue: 50
      S2:
        LedIndex: 70
        Adc: 1
        AdcChannel: 0
        TriggerValue: 60
      S3:
        LedIndex: 124
        Adc: 1
        AdcChannel: 5
        TriggerValue: 52
