SensorLED:
  Enabled: true
  RunUpMillis: 5
  RunDownMillis: 30
  HoldSeconds: 10
  LedRed: 80
  LedGreen: 80
  LedBlue: 80

NightLED:
  Enabled: true
  Latitude: 49.014
  Longitude: 8.4043
  LedRed: 4
  LedGreen: 0
  LedBlue: 0

HoldLED:
  Enabled: true
  HoldMinutes: 5
  TriggerSeconds: 3
  TriggerValue: 155
  LedRed: 160
  LedGreen: 160
  LedBlue: 160

Hardware:
  Display:
    LedsTotal: 125
    ColorCorrRed: 1.0
    ColorCorrGreen: 0.18
    ColorCorrBlue: 0.02
  Sensors:
    TriggerLeft: 60
    TriggerMidLeft: 60
    TriggerMidRight: 60
    TriggerRight: 55
    SmoothingSize: 3
    LoopDelayMillis: 5 
